TrajectoryPlannerROS:

  # Current limits based on AZ3 standalone configuration.
  acc_lim_x:  0.75
  acc_lim_y:  0.75
  acc_lim_theta: 4.00
  # min_vel_x and max_rotational_vel were set to keep the ICR at
  # minimal distance of 0.48 m. 
  # Basically, max_rotational_vel * rho_min <= min_vel_x
  max_vel_x:  0.700
  min_vel_x:  0.24
  max_rotational_vel: 0.5
  min_in_place_rotational_vel: 0.15

  xy_goal_tolerance:  0.20
  yaw_goal_tolerance: 0.20

  sim_time: 1.5
  vtheta_samples: 30

  meter_scoring: true

#global planner 
NavfnROS:
    allow_unknown: false
    visualize_potential: true
