obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[ 0.3,  0.3], [-0.3,  0.3], [-0.3, -0.3], [ 0.3, -0.3]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {data_type: LaserScan, topic: base_scan, marking: true, clearing: true}

point_cloud_sensor: {data_type: PointCloud2, topic: openni_points, marking: true, clearing: true}
